name: Flake8 Check

on:
  pull_request_target:
    branches:
      - main
      - Dev

jobs:
  flake8:
    name: Run Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        id: flake_8
        run: |
          flake8
        continue-on-error: true

      - name: Comment on PR
        if: ${{ steps.flake_8.outcome == 'failure'}}
        uses: actions/github-script@v6
        with:
          script: |
            const output = "Flake8 found issues in your code. Please fix them.\n\n ${{ steps.flake_8.outputs.stdout}}";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
